### ISSUE TITLE
只是想说这个项目很有趣

### ISSUE THREAD

**Issue by laike9m** [bbtfr/bilibili-invite-quiz#1]
支持一记，虽然我完全不会ruby吧
当初和同学答题然后各种百度

**Comment by bbtfr** [comment]
@laike9m 哈 有人关注的项目还是让人很有动力呢
不过这项目由于时间精力的原因 写了个机器人脚本偷题库以后就没太动了

**Comment by bbtfr** [comment]
看了下你资料 原来是同学 我是信工所的

**Comment by laike9m** [comment]
我看到你是信工所的了，应该是师兄吧，我现在研一

**Comment by bbtfr** [comment]
看了看你的github 总觉得github被你用来做了不少奇怪的事儿啊 哈哈哈~
博客很赞 加油~

原始邮件
发件人:Yao Zuonotifications@github.com
收件人:bbtfr/bilibili-invite-quizbilibili-invite-quiz@noreply.github.com
抄送:Theobbtfrr@gmail.com
发送时间:2014年5月16日(周五) 14:33
主题:Re: [bilibili-invite-quiz] 只是想说这个项目很有趣 (#1)

我看到你是信工所的了，应该是师兄吧，我现在研一 

 On 5/16/14, Theo notifications@github.com wrote: 
  看了下你资料 原来是同学 我是信工所的 

---

**Comment by laike9m** [comment]
嘛。。大部分项目还是很正常的
师兄在开源协会的群里吗？方便加个qq认识一下么，1215547227

**Comment by qdsang** [comment]
这个项目很有趣 +1
